### NEW USER

POST http://localhost:5500/signup/user
Content-Type: application/json

{
    "username": "Robert",
    "password": "hello",
    "email": "robert@rit.edu"
} 

### LOGIN USER


POST http://localhost:5500/login/user/
Content-Type: application/json

{
    "username": "dm9375",
    "password": "hello"
}



### NEW MANAGER


POST http://localhost:5500/add/manager
Content-Type: application/json

{
    "firstName": "Daniel",
    "lastName": "Michaels",
    "birthDate": "1966-06-6"
}


### GET MANAGERS

GET http://localhost:5500/receive/managers/Daniel%20Mironiuk
Content-Type: application/json


### UPDATE USER WITH A MANAGER WHEN RATED

PUT http://localhost:5500/update/user/manager/64a4de975b627235b5f5428f
Content-Type: application/json

{
    "managers": ["64a4dea45b627235b5f54292"]
}


### UPDATE MANAGER WITH A USER WHEN RATED

PUT http://localhost:5500/update/manager/user/64a4dea45b627235b5f54292
Content-Type: application/json

{
    "users": ["64a4de975b627235b5f5428f"]
}

### UPDATE MANAGER WITH A COMPANY WHEN RATED

PUT http://localhost:5500/update/manager/company/64a73066395535b096639d6a
Content-Type: application/json

{
    "companies": ["Google", "Facebook"]
}


### New Rating

POST http://localhost:5500/add/rating
Content-Type: application/json

{
    "user": "64a4de975b627235b5f5428f",
    "manager": "64a4dea45b627235b5f54292",
    "company": "Google",
    "rating": 3,
    "description": "This is a rating of a manager"
}

### GET Ratings for manager

GET http://localhost:5500/receive/ratings/64a4dea45b627235b5f54292
Content-Type: application/json


